### ISSUE TITLE
Documentation Diagrams

### ISSUE THREAD

**Issue by lucas-manuel** [maple-labs/maple-core#226]
![MapleFinance (2)](https://user-images.githubusercontent.com/44272939/108751714-8d91c800-7510-11eb-9efa-c9bab86e878c.png)

**Comment by lucas-manuel** [comment]
![maple-dark](https://user-images.githubusercontent.com/44272939/116272468-ec610100-a74e-11eb-808c-63ca36212b7f.png)

**Comment by lucas-manuel** [comment]
![9emt-CJQ](https://user-images.githubusercontent.com/44272939/116272804-33e78d00-a74f-11eb-97ab-77b7e13dc663.png)

**Comment by lucas-manuel** [comment]
![images](https://user-images.githubusercontent.com/44272939/119030812-5f3d5080-b978-11eb-8528-728098905658.png)

**Comment by lucas-manuel** [comment]
![2195399-200](https://user-images.githubusercontent.com/44272939/119403305-1ead4200-bcac-11eb-87a2-6e5add888263.png)

**Comment by lucas-manuel** [comment]
![bot_icon_still_2x](https://user-images.githubusercontent.com/44272939/119403440-5916df00-bcac-11eb-9719-f103e8aadb34.gif)

**Comment by lucas-manuel** [comment]
![alert-icon-1562](https://user-images.githubusercontent.com/44272939/119428214-7cf11980-bcda-11eb-87bd-cbf36f1d2066.png)

**Comment by lucas-manuel** [comment]
![bot_icon_still_2x](https://user-images.githubusercontent.com/44272939/119591600-e76e8c00-bda4-11eb-966c-ef3f7d306f55.gif)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 24 16 AM](https://user-images.githubusercontent.com/44272939/141297639-ab5f6b2f-e14e-4006-b79a-ab250af3eb5a.png)

![Screen Shot 2021-11-11 at 7 22 53 AM](https://user-images.githubusercontent.com/44272939/141297645-4ad5e9ae-42d7-426c-b0bd-c69994890c7e.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 37 25 AM](https://user-images.githubusercontent.com/44272939/141299394-9423da66-b705-439b-a2a5-277989213349.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 43 18 AM](https://user-images.githubusercontent.com/44272939/141300053-ec641872-db38-4963-886f-9fe20136891d.png)
![Screen Shot 2021-11-11 at 7 41 51 AM](https://user-images.githubusercontent.com/44272939/141300058-e1d35838-7a40-47c0-92d9-c03f46e3729c.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 45 46 AM](https://user-images.githubusercontent.com/44272939/141300403-20d177ee-b3ee-4ffa-8767-93d229f0ea18.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 48 38 AM](https://user-images.githubusercontent.com/44272939/141300713-1db5158b-1aa0-4dd5-81ce-a0d73f322449.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 7 57 18 AM](https://user-images.githubusercontent.com/44272939/141301924-34b77979-3de8-45ad-9a7d-b8102eb8b23d.png)
![Screen Shot 2021-11-11 at 7 56 38 AM](https://user-images.githubusercontent.com/44272939/141301926-56736112-b082-49b5-b71f-07ac44d070cb.png)
![Screen Shot 2021-11-11 at 7 55 38 AM](https://user-images.githubusercontent.com/44272939/141301928-750be262-31c4-4a70-b135-f784a87634a8.png)
![Screen Shot 2021-11-11 at 7 54 40 AM](https://user-images.githubusercontent.com/44272939/141301929-2b7da85c-c255-4e05-9a68-7d878c03cd99.png)
![Screen Shot 2021-11-11 at 7 53 45 AM](https://user-images.githubusercontent.com/44272939/141301931-b020131e-923e-4f22-bbd2-9f210b042853.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 1 17 23 PM](https://user-images.githubusercontent.com/44272939/141348909-7555cbbe-a54a-42af-afce-a1718232d293.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-11 at 1 20 17 PM](https://user-images.githubusercontent.com/44272939/141349250-ddb579f8-76ab-4d61-916b-119d952ed73e.png)
![Screen Shot 2021-11-11 at 1 19 40 PM](https://user-images.githubusercontent.com/44272939/141349251-4397c984-9087-4b45-91de-1e3493ae1541.png)

**Comment by lucas-manuel** [comment]
![LoanV2 Default Flow](https://user-images.githubusercontent.com/44272939/141701923-611861f7-4c2c-43cd-a6c8-6e1d175e8b1c.png)

![LoanV2 Payment Flow](https://user-images.githubusercontent.com/44272939/141701929-5aa3a44e-7a7e-404f-8f2b-370a9ae51fdf.png)

![LoanV2 Refinance Flow](https://user-images.githubusercontent.com/44272939/141701944-1bfa68b5-c6c3-4c71-9c05-3a1ea0215c92.png)

**Comment by lucas-manuel** [comment]
![MapleLoanFactory Proxy Diagram](https://user-images.githubusercontent.com/44272939/141702572-991685e5-9a4e-4fd5-bd8c-1f0e43350eb8.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-16 at 10 15 35 AM](https://user-images.githubusercontent.com/44272939/142012318-d2ee4c2d-3f6c-444c-9536-4efc6d079175.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2021-11-16 at 10 25 36 AM](https://user-images.githubusercontent.com/44272939/142014126-7851f15e-3ebb-427d-8d4e-455517906024.png)

**Comment by lucas-manuel** [comment]
![MapleLoanFactory Proxy Diagram - V2 - Upgrade](https://user-images.githubusercontent.com/44272939/142018369-fe980591-8e03-497b-8814-cc3565263ba9.png)

**Comment by lucas-manuel** [comment]
![LoanV2 Refinance Flow - Small](https://user-images.githubusercontent.com/44272939/142057300-771caf22-899b-403d-a0bb-7093beb3caa9.png)

**Comment by lucas-manuel** [comment]
![Repossession Conditions](https://user-images.githubusercontent.com/44272939/142061745-0fd6bcb2-60d8-435b-a8bc-5b1649f98370.png)

**Comment by lucas-manuel** [comment]
![Repossession Conditions (1)](https://user-images.githubusercontent.com/44272939/142062302-05d024a8-5b3e-4394-b06d-5b5149106f91.png)

**Comment by lucas-manuel** [comment]
![LoanV2 Default Flow - Small](https://user-images.githubusercontent.com/44272939/142064007-632c330c-f087-412f-8bc8-a818546d8fb7.png)

**Comment by JGcarv** [comment]
![Migration Diagrams](https://user-images.githubusercontent.com/16119563/156415169-75b2d7b4-8466-447c-b9ad-f9b94d3f6546.jpeg)

**Comment by edag94** [comment]
![image](https://user-images.githubusercontent.com/22627847/156423942-12f82a68-d7f4-4422-9300-3bc0ef4d8bea.png)

**Comment by edag94** [comment]
![image](https://user-images.githubusercontent.com/22627847/156435230-3bd58d60-2fe5-4f69-ae26-5220fa9c9cd2.png)

**Comment by edag94** [comment]
![image](https://user-images.githubusercontent.com/22627847/156435725-4d8daa09-0d6a-4b05-b2cb-ed9c5ce11bd5.png)

**Comment by JGcarv** [comment]
![Migration Diagrams](https://user-images.githubusercontent.com/16119563/156451625-aaf01596-4cb2-4eff-8e0f-380897592afa.svg)

**Comment by lucas-manuel** [comment]
![Screen Shot 2022-03-02 at 3 23 00 PM](https://user-images.githubusercontent.com/44272939/156452018-1c050560-2ce8-43b2-b006-9c1553a96a14.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2022-03-02 at 3 30 47 PM](https://user-images.githubusercontent.com/44272939/156452931-4de8b65c-6e24-4a55-b44c-ddd8e4a07788.png)

**Comment by lucas-manuel** [comment]
![Screen Shot 2022-03-02 at 3 31 21 PM](https://user-images.githubusercontent.com/44272939/156452984-f0eca70d-dfca-4b84-85e7-8b3ca92fa8d6.png)

**Comment by lucas-manuel** [comment]
![Standalone Migration](https://user-images.githubusercontent.com/44272939/156459804-d0aecf37-7eb0-4359-b415-28fe041d4077.png)
![One Time xMPL Migration](https://user-images.githubusercontent.com/44272939/156459811-1a4b623c-932a-4ac4-b9e7-147ccfa1c6ca.png)

**Comment by lucas-manuel** [comment]
![Update Vesting Schedule Diagram](https://user-images.githubusercontent.com/44272939/156641535-353acbcf-b4af-4e4d-8e90-fe70b57ee348.png)

**Comment by lucas-manuel** [comment]
![Update Vesting Schedule Diagram](https://user-images.githubusercontent.com/44272939/156643098-fb7cf6e4-91c3-477f-a59c-a1a6c5cf6dc8.svg)

**Comment by lucas-manuel** [comment]
https://code4rena.com/reports/2022-03-maple
